version: 2.1

orbs:
  gcp-gke: circleci/gcp-gke@0.2.0

jobs:
  order_complete_updater:
    working_directory: ~/order-complete-updater
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: order-complete-updater-{{ checksum "order-complete-updater/pom.xml" }}
      - run:
          name: Downloading dependencies
          command: cd order-complete-updater && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: order-complete-updater-{{ checksum "order-complete-updater/pom.xml" }}
      - run:
          name: Building jar
          command: cd order-complete-updater && mvn package
      - run:
          name: Logging in on the docker hub
          command: cd order-complete-updater && docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run:
          name: Building docker image
          command: cd order-complete-updater && docker image build . -t devopsgreenhouse/order-complete-updater:$CIRCLE_SHA1
      - run:
          name: Pushing docker image
          command: cd order-complete-updater && docker image push devopsgreenhouse/order-complete-updater:$CIRCLE_SHA1
      #- store_test_results:
      #    path:
      #- store_artifacts:
      #    path:

  order_service:
    working_directory: ~/order-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: order-service-{{ checksum "order-service/pom.xml" }}
      - run:
          name: Downloading dependencies
          command: cd order-service && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: order-service-{{ checksum "order-service/pom.xml" }}
      - run:
          name: Building jar
          command: cd order-service && mvn package
      - run:
          name: Logging in on the docker hub
          command: cd order-service && docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run:
          name: Building docker image
          command: cd order-service && docker image build . -t devopsgreenhouse/order-service:$CIRCLE_SHA1
      - run:
          name: Pushing docker image
          command: cd order-service && docker image push devopsgreenhouse/order-service:$CIRCLE_SHA1
      #- store_test_results:
      #    path:
      #- store_artifacts:
      #    path:

  payment_distribution:
    working_directory: ~/payment-distribution
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: payment-distribution-{{ checksum "payment-distribution/pom.xml" }}
      - run:
          name: Downloading dependencies
          command: cd payment-distribution && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: payment-distribution-{{ checksum "payment-distribution/pom.xml" }}
      - run:
          name: Building jar
          command: cd payment-distribution && mvn package
      - run:
          name: Logging in on the docker hub
          command: cd payment-distribution && docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run:
          name: Building docker image
          command: cd payment-distribution && docker image build . -t devopsgreenhouse/payment-distribution:$CIRCLE_SHA1
      - run:
          name: Pushing docker image
          command: cd payment-distribution && docker image push devopsgreenhouse/payment-distribution:$CIRCLE_SHA1
      #- store_test_results:
      #    path:
      #- store_artifacts:
      #    path:

  payment_service:
    working_directory: ~/payment-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: payment-service-{{ checksum "payment-service/pom.xml" }}
      - run:
          name: Downloading dependencies
          command: cd payment-service && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: payment-service-{{ checksum "payment-service/pom.xml" }}
      - run:
          name: Building jar
          command: cd payment-service && mvn package
      - run:
          name: Logging in on the docker hub
          command: cd payment-service && docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run:
          name: Building docker image
          command: cd payment-service && docker image build . -t devopsgreenhouse/payment-service:$CIRCLE_SHA1
      - run:
          name: Pushing docker image
          command: cd payment-service && docker image push devopsgreenhouse/payment-service:$CIRCLE_SHA1
      #- store_test_results:
      #    path:
      #- store_artifacts:
      #    path:

  restaurant_service:
    working_directory: ~/restaurant-service
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: restaurant-service-{{ checksum "restaurant-service/pom.xml" }}
      - run:
          name: Downloading dependencies
          command: cd restaurant-service && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: restaurant-service-{{ checksum "restaurant-service/pom.xml" }}
      - run:
          name: Building jar
          command: cd restaurant-service && mvn package
      - run:
          name: Logging in on the docker hub
          command: cd restaurant-service && docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run:
          name: Building docker image
          command: cd restaurant-service && docker image build . -t devopsgreenhouse/restaurant-service:$CIRCLE_SHA1
      - run:
          name: Pushing docker image
          command: cd restaurant-service && docker image push devopsgreenhouse/restaurant-service:$CIRCLE_SHA1
      #- store_test_results:
      #    path:
      #- store_artifacts:
      #    path:

  hystrix_dashboard:
    working_directory: ~/hystrix-dashboard
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: hystrix-dashboard-{{ checksum "hystrix-dashboard/pom.xml" }}
      - run:
          name: Downloading dependencies
          command: cd hystrix-dashboard && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: hystrix-dashboard-{{ checksum "hystrix-dashboard/pom.xml" }}
      - run:
          name: Building jar
          command: cd hystrix-dashboard && mvn package
      - run:
          name: Logging in on the docker hub
          command: cd hystrix-dashboard && docker login -u ${DOCKER_USER} -p ${DOCKER_PW}
      - run:
          name: Building docker image
          command: cd hystrix-dashboard && docker image build . -t devopsgreenhouse/hystrix-dashboard:$CIRCLE_SHA1
      - run:
          name: Pushing docker image
          command: cd hystrix-dashboard && docker image push devopsgreenhouse/hystrix-dashboard:$CIRCLE_SHA1
      #- store_test_results:
      #    path:
      #- store_artifacts:
      #    path:

  deploy:
    machine: true
    steps:
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          cluster: greenhouse-delivery
          deployment: order-complete-updater
          container: order-complete-updater
          image: devopsgreenhouse/order-complete-updater:$CIRCLE_SHA1
      - gcp-gke/rollout-image:
          cluster: greenhouse-delivery
          deployment: order-service
          container: order-service
          image: devopsgreenhouse/order-service:$CIRCLE_SHA1
      - gcp-gke/rollout-image:
          cluster: greenhouse-delivery
          deployment: payment-distribution
          container: payment-distribution
          image: devopsgreenhouse/payment-distribution:$CIRCLE_SHA1
      - gcp-gke/rollout-image:
          cluster: greenhouse-delivery
          deployment: payment-service
          container: payment-service
          image: devopsgreenhouse/payment-service:$CIRCLE_SHA1
      - gcp-gke/rollout-image:
          cluster: greenhouse-delivery
          deployment: restaurant-service
          container: restaurant-service
          image: devopsgreenhouse/restaurant-service:$CIRCLE_SHA1
      - gcp-gke/rollout-image:
          cluster: greenhouse-delivery
          deployment: hystrix-dashboard
          container: hystrix-dashboard
          image: devopsgreenhouse/hystrix-dashboard:$CIRCLE_SHA1

workflows:
  version: 2
  build_test:
    filters:
        branches:
            ignore: master
    jobs:
      - order_complete_updater
      - order_service
      - payment_distribution
      - payment_service
      - restaurant_service
      - hystrix_dashboard
  build_test_and_deliver:
    filters:
        branches:
            only: master
    jobs:
      - order_complete_updater
      - order_service
      - payment_distribution
      - payment_service
      - restaurant_service
      - hystrix_dashboard
      - deploy:
          requires:
            - order_complete_updater
            - order_service
            - payment_distribution
            - payment_service
            - restaurant_service
            - hystrix_dashboard
