server:
  port: 80
spring:
  application:
    name: payment-service
  cloud:
    stream:
      bindings:
        input: payments
  data:
    mongodb:
      host: mongo
  rabbitmq:
    host: rabbitmq
logging:
  path: logs-payment-service/
  file: logs-payment-service/app.log
