server:
  port: 80
spring:
  application:
    name: payment-distribution
  cloud:
    stream:
      bindings:
        output: payments
  rabbitmq:
    host: rabbitmq
logging:
  path: logs-payment-distribution/
  file: logs-payment-distribution/app.log
